#!/bin/sh
set -eu
SYNOWAKE_PKGDEST="${SYNOPKG_PKGDEST:-/var/packages/h5uSynoWake/target}"
SYNOWAKE_VAR="${SYNOPKG_PKGVAR:-/var/packages/h5uSynoWake/var}"
export SYNOWAKE_PKGDEST SYNOWAKE_VAR
exec "$SYNOWAKE_PKGDEST/bin/synowake" init
